### ISSUE TITLE
BlTextDecorationAttribute fails

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Alexandrie#10]
This example do not work :
example_EditorAsTextAreaWithHighlight

	| ed space text |
	ed := AlbEditor new.
	text := 'AB  CD' asRopedText.
	"text attribute: (BlTextBackgroundAttribute paint: (Color blue alpha: 0.3)) from: 1 to: 1."
	text attribute: (BlTextBackgroundAttribute paint: (Color yellow alpha: 0.5)) from: 3 to: 3.
	text attribute: (BlTextDecorationAttribute new wavy color: Color blue) from: 4 to: 6.
	"text attribute: (BlTextBackgroundAttribute paint: (Color yellow alpha: 0.5)) from: 2 to: 2."
	"text attribute: (BlTextBackgroundAttribute paint: (Color red alpha: 0.3)) from: 3 to: 3."
	text
		fontSize: 24;
		fontName: 'Helvetica Neue'.
	ed text: text.
	space := BlSpace new.
	space root addChild: ed.
	space title: 'editor'.
	"ed inspect."

	space show.
	^ ed

**Comment by plantec** [comment]
<img width="683" alt="Capture d’écran 2022-07-27 à 20 07 29" src="https://user-images.githubusercontent.com/435221/181342174-4111cd18-facf-4780-8508-d7bab5f7d66e.png">

**Comment by tinchodias** [comment]
This is old, no?

**Comment by tinchodias** [comment]
Still happens

**Comment by tinchodias** [comment]
Reproduce with:
```
| ed space text |
ed := AlbEditorElement new.
text := 'abcd' asRopedText.
text
	attribute: (BlTextDecorationAttribute new wavy color: Color blue)
	from: 1
	to: 2.
ed text: text.

space := BlSpace new.
space root addChild: ed.
space show
```

then you can clean up with:
```
BlOSWindowSDL2Host universe closeSpaces.
BlOSWindowSDL2Host stop; start.
```

**Comment by tinchodias** [comment]
There is no error anymore. It is ignored silently. 
Implementation request is here: https://github.com/pharo-graphics/Bloc/issues/328
