### ISSUE TITLE
alexandrieFixedMeasurer

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Alexandrie#11]
The package Bloc-Alexandrie fails to load given it includes alexandrieFixedMeasurer, an extension to an Album class.

I think we should move it to Album, and make Bloc-Alexandrie loaded by default.

@plantec ?

**Comment by plantec** [comment]
ah, yes of course...
 I will do it

**Comment by tinchodias** [comment]
I can do it, don't worry, only wanted to tell you before
