### ISSUE TITLE
BlRoundedRectangle drawing transpose element bounds

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Alexandrie#15]
| e |
e := BlElement new.
e geometry: (BlRoundedRectangleGeometry cornerRadius: 20).
e border: (BlBorder paint: Color blue width: 2).
e size: 200@30.
e openInOBlSpace 

<img width="619" alt="Capture d’écran 2022-10-24 à 20 15 46" src="https://user-images.githubusercontent.com/435221/197596910-fc0238ac-3281-48bf-afd4-15c3d08de394.png">

**Comment by tinchodias** [comment]
Ooops :) strange, render test needed!

I add a todo.
