### ISSUE TITLE
Rounded corner is rendered even in a zero sized element 

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Alexandrie#28]
example:
BlElement new 
	constraintsDo: [ :c | c horizontal fitContent. c vertical fitContent]; 
	border: (BlBorder paint: Color gray);
	geometry: (BlRoundedRectangleGeometry cornerRadius: 24); 
	openInOBlSpace.

<img width="97" alt="Capture d’écran 2023-04-04 à 23 50 01" src="https://user-images.githubusercontent.com/435221/229930490-e335cdd1-7c9e-4398-90d8-893b2ad55308.png">

**Comment by tinchodias** [comment]
Ooops! In fact, have to add a test for all geometries with 0@0 size!

**Comment by plantec** [comment]
I've also cases where the debugger opens on a divide by zero exception.
I tried to reproduce it with an example but with our success. No doubt that it is when the element has a zero size

**Comment by tinchodias** [comment]
The fix corresponds to Bloc's repo. I pushed a commit there that seems to close this issue.

**Comment by tinchodias** [comment]
This is fixed.

I tried these two examples to check it:
```
BlElement new
	position: 50 asPoint;
	size: 0 asPoint;
	border: (BlBorder paint: Color black);
	geometry: (BlRoundedRectangleGeometry cornerRadius: 50);
	openInSpace.

BlElement new
	position: 50 asPoint;
	constraintsDo: [ :c |
		c horizontal fitContent.
		c vertical fitContent ];
	border: (BlBorder paint: Color black);
	geometry: (BlRoundedRectangleGeometry cornerRadius: 24);
	openInSpace.
```
