### ISSUE TITLE
Rendering round corner in a zero sized element raises a ZeroDivide error

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Alexandrie#29]
It raises an error.

an example with ToSandbox class >> example_BasicComboBox

https://user-images.githubusercontent.com/435221/230668298-e1fa2a14-0363-43a5-be08-092dbef4a471.mov

**Comment by tinchodias** [comment]
The fix corresponds to Bloc's repo. I pushed a commit there that seems to close this issue.

**Comment by tinchodias** [comment]
Yes, this should be fixed, same as https://github.com/pharo-graphics/Alexandrie/issues/28
