### ISSUE TITLE
BlSpaceBuilder uses BlMorphicWindowHost ?

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Alexandrie#4]
Shouldn't it use BAMorphicWindowHost ?

BlSpaceBuilder>>initialize

	super initialize.
	
	space := BlSpace new.
	spaceExtent := 100 asPoint.
	host := BlMorphicWindowHost new.
....

**Comment by tinchodias** [comment]
Yes, we can change it. 
I'm not sure about the whole BlSpaceBuilder, in fact. I wrote it with the goal of reduce the length of the test examples (which I called fixtures).
