### ISSUE TITLE
BlHost should be abstract and should not depend on Sparta

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Alexandrie#5]
"This is a feature expected from any BlHost but creates a dependency to Sparta" flag in containsPoint: element: geometry:, offscreenMeasureTextParagraph: and visualBoundsOf:.
Maybe we should have a look at the GlamorousToolkit version which seems better designed.

**Comment by plantec** [comment]
It is more a Bloc issue but introducing Alexandrie is a good occasion to revise BlHost

**Comment by tinchodias** [comment]
+1
Yes, I wrote that comment when I extracted that code from some class, maybe BlGeometry.

**Comment by tinchodias** [comment]
This is fixed now that Sparta was removed
