### ISSUE TITLE
Text attribute rendering issue

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Alexandrie#6]
Strange drawing behavior. #pathTranslate: related ?
Here is an example. See screenshots for results with Sparta/Cairo and with Alexandrie
<img width="92" alt="Capture d’écran 2022-07-20 à 15 34 36" src="https://user-images.githubusercontent.com/435221/179996562-8caec78c-49d7-4e4d-b015-458fc8c0798f.png">
<img width="219" alt="Capture d’écran 2022-07-20 à 15 35 22" src="https://user-images.githubusercontent.com/435221/179996555-e79a0302-2ee9-4be0-9341-5a683a63f6aa.png">
```
| text space |
text := 'ABCD' asRopedText.
text attribute: (BlTextBackgroundAttribute paint: (Color blue alpha: 0.3)) from: 1 to: 1.
text attribute: (BlTextBackgroundAttribute paint: (Color yellow alpha: 0.5)) from: 2 to: 2.
text attribute: (BlTextBackgroundAttribute paint: (Color red alpha: 0.3)) from: 3 to: 3.
text
	fontSize: 24;
	fontName: 'Helvetica Neue'.
space := BlSpace new.
space root addChild: text asElement.
space title: 'attribute drawing issue'.
space show.
```

**Comment by tinchodias** [comment]
Thanks for the report!
I add a todo on my notes to test it.
Right now, the PCRenderingText is not properly working but not far from running it by CI.
