### ISSUE TITLE
Add "pathRotate" method in AeCanvas

### ISSUE THREAD

**Issue by labordep** [pharo-graphics/Alexandrie#62]
Hi @tinchodias,
I propose to add a AeCanvas>>pathRotate: method

Here an example of my actual usage (dirty because I'm not manage the rotation center yet):

```
self rotation ~= 0.0 ifTrue:[ | matrix radians |
	matrix := AeCairoMatrix newIdentity.
	radians := self rotation degreesToRadians.
	matrix rotateByRadians: radians.
	aeCanvas pathTransform: matrix.  	
].
```

**Comment by tinchodias** [comment]
Hello @Pierre. 
This page shows C code for rotation around a point: https://www.cairographics.org/cookbook/transform_about_point/

I think the equivalent would be:
```
self rotation ~= 0.0 ifTrue:[ | matrix |
	matrix := AeCairoMatrix newIdentity.
	matrix
		translateBy: self rotationCenter;
		rotateByRadians: self rotation degreesToRadians;
		translateBy: self rotationCenter negated.

	aeCanvas pathTransform: matrix.  	
].
```

**Comment by labordep** [comment]
Hi @tinchodias, 

To be more clear regarding your link, I think the equivalent will be:

```
self rotation ~= 0.0 ifTrue:[
	aeCanvas rotate: self rotation.  	
].
```

 Because I alteady use a Matrix, it is working very nice but it should be great to directly do the rotation on the Canvas without using a Matrix.

The stuff to manage the center is optional (and it's works in fact).
