### ISSUE TITLE
tab width too small

### ISSUE THREAD

**Issue by plantec** [pharo-graphics/Alexandrie#7]
in Alexandrie, the tab width is too small

<img width="162" alt="Capture d’écran 2022-07-21 à 17 16 53" src="https://user-images.githubusercontent.com/435221/180251432-451acd11-8e8f-4ded-8c2e-920927473b8d.png">

**Comment by tinchodias** [comment]
I realized that Sparta doesn't align but only replaces tab character by 4 spaces (see Character>>#textRunOn:).

Rubric does align:

<img width="293" alt="Screen Shot 2022-07-22 at 18 19 25" src="https://user-images.githubusercontent.com/3044265/180575874-8dc2d293-2700-42df-817a-5ab9e741aefc.png">

Code:

```smalltalk
stringWithTabs := '
A	A
AA	A
AAA	A
'.

RubEditingArea new
	font: (LogicalFont familyName: 'Source Sans Pro' pointSize: 20);
	updateTextWith: stringWithTabs;
	tabWidth: 100;
	openInWindow.
	
editor := AlbEditor new
	text: stringWithTabs asRopedText;
	yourself.
space := BlSpace new.
space root addChild: editor.
space show.
```

**Comment by tinchodias** [comment]
Debugging I see:

the editor has a current paragraph, then:
a paragraph has a `RubTextComposer`
--> a `RubTextComposer` has a `TextStyle`
----> `TextStyle` uses `TextConstants`
------> `TextConstants` defines `DefaultTabsArray` as `#(24 48 72 96 120 144 168 ... 936 960)`
and that's the default tab stops.

I wonder if our editor has equivalent text style and composer.

Pango seems to implement it similarly, you can just set a default tab width, or set an array of tab stops:
https://docs.gtk.org/Pango/struct.TabArray.html


btw, I've found interesting this elastic tabs, but didn't try it:
https://nickgravgaard.com/elastic-tabstops/

**Comment by tinchodias** [comment]
Do you think we can fix this more correctly like in Rubric? or it could be an easy workaround to do like Sparta, do a pass before rendering and convert each tab to certain number of spaces.

**Comment by plantec** [comment]
Character>>#textRunOn: ... :))
rrrrrrahhhh, shitty, could have seen it by myself

**Comment by plantec** [comment]
yes, Rubric handles tab a much clever way. I will think about that. it should be possible to change that.
Thanks, this is an Album issue now.
Regarding elastic tab: interesting, I will see how to allow such a feature in the futur
